package com.moon.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-03-19T17:18:30.198+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "WeatherWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WeatherWebServiceHttpPost {

    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getSupportProvince();

    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getWeatherbyCityNamePro(
        @WebParam(partName = "theCityName", name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theCityName,
        @WebParam(partName = "theUserID", name = "theUserID", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theUserID
    );

    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getSupportCity(
        @WebParam(partName = "byProvinceName", name = "byProvinceName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String byProvinceName
    );

    @WebMethod
    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public DataSet getSupportDataSet();

    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getWeatherbyCityName(
        @WebParam(partName = "theCityName", name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theCityName
    );
}
